root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-extra-semi': off
