const lines: Record<
  string,
  (name: string, require: (name: string) => string) => string[]
> = {
  yes: name => [`function ${name}(value) {`, '  return value;', '}'],

  ok: name => [`function ${name}(value) {`, '  return [0, value];', '}'],

  err: name => [`function ${name}(value) {`, '  return [1, value];', '}'],

  'int.intInBase10': name => [
    `function ${name}(int) {`,
    '  return int.toString();',
    '}',
  ],

  'float.round': name => [
    `function ${name}(n) {`,
    '  if (isFinite(n)) {',
    '    return Math.round(n);',
    '  } else {',
    '    return 0;',
    '  }',
    '}',
  ],

  'float.floor': name => [
    `function ${name}() {`,
    '  if (isFinite(n)) {',
    '    return Math.floor(n);',
    '  } else {',
    '    return 0;',
    '  }',
    '}',
  ],

  'float.ceil': name => [
    `function ${name}() {`,
    '  if (isFinite(n)) {',
    '    return Math.ceil(n);',
    '  } else {',
    '    return 0;',
    '  }',
    '}',
  ],

  'char.charCode': name => [
    `function ${name}(char) {`,
    '  if (char.length === 1) {',
    '    return char.charCodeAt(0);',
    '  } else {',
    '    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt#fixing_charcodeat_to_handle_non-basic-multilingual-plane_characters_if_their_presence_earlier_in_the_string_is_unknown',
    '    return (',
    '      (char.charCodeAt(0) - 0xd800) * 0x400 +',
    '      (char.charCodeAt(1) - 0xdc00) +',
    '      0x10000',
    '    );',
    '  }',
    '}',
  ],

  'int.intCode': name => [
    `function ${name}(code) {`,
    '  if (code < 0 || code > 0x10ffff || (code >= 0xd800 && code <= 0xdfff)) {',
    '    return "\\uFFFD";',
    '  } else if (code > 0xffff) {',
    '    code -= 0x10000;',
    '    return String.fromCharCode(',
    '      Math.floor(code / 0x400) + 0xd800,',
    '      (code % 0x400) + 0xdc00',
    '    );',
    '  } else {',
    '    return String.fromCharCode(code);',
    '  }',
    '}',
  ],

  'str.charAt': name => [
    `function ${name}(string) {`,
    '  return function (index) {',
    '    if (index < 0) {',
    '      // Return none',
    '      return function () {};',
    '    } else {',
    '      if (index >= string.length * 2) {',
    '        // Early exit, assuming the worst case where the string is full of',
    '        // surrogate pairs',
    '        return;',
    '      }',
    '      var i = 0;',
    '      var codePoint;',
    '      for (var j = 0; j < index; j++) {',
    '        codePoint = string.charCodeAt(i);',
    '        if (codePoint >= 0xd800 && codePoint <= 0xdbff) {',
    '          // Assumes the string is well-formed UTF-8',
    '          i += 2;',
    '        } else {',
    '          ++i;',
    '        }',
    '        if (i >= string.length) return;',
    '      }',
    '      codePoint = string.charCodeAt(i);',
    '      if (codePoint >= 0xd800 && codePoint <= 0xdbff) {',
    '        return string.slice(i, i + 2);',
    '      } else {',
    '        return string[i];',
    '      }',
    '    }',
    '  };',
    '}',
  ],

  'str.substring': name => [
    `function ${name}(string) {`,
    '  return function (start) {',
    '    return function (end) {',
    '      if (start === end || (start >= 0 && end >= 0 && start > end)) {',
    '        return "";',
    '      } else {',
    '        return string.slice(start, end);',
    '      }',
    '    };',
    '  };',
    '}',
  ],

  'str.len': name => [
    `function ${name}(value) {`,
    '  var highSurrogates = 0;',
    '  for (var i = 0; i < value.length; i++) {',
    '    var codePoint = value.charCodeAt(i);',
    '    if (codePoint >= 0xd800 && codePoint <= 0xdbff) {',
    '      ++highSurrogates;',
    '    }',
    '  }',
    '  // Subtract a surrogate from each pair',
    '  return value.length - highSurrogates;',
    '}',
  ],

  'list.len': name => [
    `function ${name}(value) {`,
    '  return value.length;',
    '}',
  ],

  'str.split': name => [
    `function ${name}(string) {`,
    '  return function (char) {',
    '    if (string === "") {',
    '      return [];',
    '    } else {',
    '      return string.split(char);',
    '    }',
    '  };',
    '}',
  ],

  'str.strip': name => [
    `function ${name}(string) {`,
    '  // String#trim: IE10+',
    '  return string.trim();',
    '}',
  ],

  range: name => [
    `function ${name}(start) {`,
    '  return function (end) {',
    '    if (start === end) {',
    '      return function () {',
    '        return [];',
    '      };',
    '    } else {',
    '      return function (step) {',
    '        if (step === 0) {',
    '          throw new Error("Undefined behaviour. See nbuilding/N-lang#246");',
    '        }',
    '        var numbers = [];',
    '        if (step > 0) {',
    '          if (end < start) {',
    '            return [];',
    '          }',
    '          for (var i = start; i < end; i += step) {',
    '            numbers.push(i);',
    '          }',
    '        } else {',
    '          if (end > start) {',
    '            return [];',
    '          }',
    '          for (var i = start; i > end; i += step) {',
    '            numbers.push(i);',
    '          }',
    '        }',
    '        return numbers;',
    '      };',
    '    }',
    '  };',
    '}',
  ],

  print: name => [
    `function ${name}(value) {`,
    '  // TODO: Prettify',
    '  console.log(value, typeof value);',
    '  return value;',
    '}',
  ],

  'list.itemAt': name => [
    `function ${name}(list) {`,
    '  return function (index) {',
    '    if (index < 0) {',
    '      return;',
    '    } else {',
    '      return list[index];',
    '    }',
    '  };',
    '}',
  ],

  'list.append': name => [
    `function ${name}(list) {`,
    '  return function (item) {',
    '    return list.concat([item]);',
    '  };',
    '}',
  ],

  'list.filterMap': name => [
    `function ${name}(list) {`,
    '  return function (transform) {',
    '    var newList = [];',
    '    for (var i = 0; i < list.length; i++) {',
    '      var result = transform(list[i]);',
    '      if (result !== undefined) {',
    '        newList.push(result);',
    '      }',
    '    }',
    '    return newList;',
    '  };',
    '}',
  ],

  'maybe.default': name => [
    `function ${name}(maybe) {`,
    '  return function (defaultValue) {',
    '    if (maybe === undefined) {',
    '      return defaultValue;',
    '    } else {',
    '      return maybe;',
    '    }',
    '  };',
    '}',
  ],

  'cmd.then': name => [
    `function ${name}(cmd) {`,
    '  return function (onCmdFinish) {',
    '    return function (callback) {',
    '      cmd(function (result) {',
    '        onCmdFinish(result)(callback);',
    '      });',
    '    };',
    '  };',
    '}',
  ],

  mapFrom: name => [
    `function ${name}(entries) {`,
    '  let out = new Map();',
    '  for (const entry of entries) {',
    '    out.set(entry[0], entry[1]);',
    '  }',
    '  return out;',
    '}',
  ],

  'map.getValue': name => [
    `function ${name}(map) {`,
    '  return function (key) {',
    '    return map.get(key);',
    '  };',
    '}',
  ],

  'map.entries': name => [
    `function ${name}(map) {`,
    '  return Array.from(map.entries());',
    '}',
  ],
}

export default lines
