name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: Run PyInstaller
        run: pyinstaller --noconfirm --onedir --console --icon "icons/n.icns" --add-data "python/syntax.lark:." --hiddenimport websockets.legacy --hiddenimport websockets.legacy.client "python/n.py"

      - name: Create Zip Archive
        uses: papeloto/action-zip@v1
        with:
          files: dist/n/
          dest: N-MacOS.zip
          
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ${{ github.workspace }}/N-MacOS.zip
          
  windows:
    runs-on: windows-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          
      - name: Run PyInstaller
        run: pyinstaller --noconfirm --onedir --console --icon "icons/n.ico" --add-data "python/syntax.lark;." --hiddenimport websockets.legacy --hiddenimport websockets.legacy.client "python/n.py"

      - name: Create Zip Archive
        uses: papeloto/action-zip@v1
        with:
          files: dist/n/
          dest: N.zip
                    
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}/N.zip
          
  release:
    needs: [mac, windows]
    runs-on: ubuntu-latest
    steps:
      
      - name: Download Release Artifacts
        uses: actions/download-artifact@v2
        
      - name: Get Tag Name
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/*/}
        
      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          name: N ${{ steps.tag.outputs.name }}
          artifacts: "macos/N-MacOS.zip,windows/N.zip"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
